image: alpine:latest

pages:
  stage: deploy
  script:
    - rm -rf .public;
    - rm -rf public;
    - mkdir .public;
    - \cp -r *.html .public;
    - \cp -r css/ .public;
    - \cp -r images/ .public;
    - \cp -r js/ .public;
    - \cp -r .public/. public;
  artifacts:
    paths:
      - public
    expire_in: 3 days
  only:
    - devel
    - main
