image: alpine:latest

pages:
  stage: deploy
  script:
    - \cp -r css/. .public
    - \cp -r images/. .public
    - \cp -r js/. .public
    - \cp -r *.html .public
    - \cp -r .public/. public
  artifacts:
    paths:
      - public
    expire_in: 10 days
  only:
    - main
